package net.motimaa.motiyhteisot.gui.items;

public enum Action {

    MANAGEROLES, EXIT, CREATE, MODIFY,
    LISTROLES, SELECTROLE, NAME, DOWN,
    UP, WEIGHT, GIVEPERMISSION, REMOVEPERMISSION,
    PERMISSIONS, CONFIRM, DENY,
    MAINPAGE, BASE, RENAME, BANK,
    CHAT, APPLIST, ROLELIST, PL_LIST, CMDLIST, HINTGIVE

}
